### PR TITLE
Fix butchering for parsnip's `bart()`

### LINKED ISSUE #262: Problem with predicting after butchering bart
In rstudio/vetiver-r#234 @JamesHWade reported a problem predicting with `bart()` used via tidymodels:

``` r
library(tidymodels)
## note that `bart()` has a pretty nasty namespace collision:
tidymodels_prefer()
data(ames)

set.seed(502)
ames_split <- ames |> 
    mutate(Sale_Price = log10(Sale_Price)) |> 
    initial_split(prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <- testing(ames_split)

ames_rec <- 
    recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + 
               Latitude + Longitude, data = ames_train) |>
    step_log(Gr_Liv_Area, base = 10) |> 
    step_other(Neighborhood, threshold = 0.01) |> 
    step_dummy(all_nominal_predictors()) |> 
    step_interact( ~ Gr_Liv_Area:starts_with("Bldg_Type_") ) |> 
    step_ns(Latitude, Longitude, deg_free = 20)


bart_model <- bart(mode = "regression")
bart_wflow <- workflow(ames_rec, bart_model)
fitted <- bart_wflow |> last_fit(ames_split) |> extract_workflow()
predict(fitted, new_data = slice_sample(ames_test, n = 1))
#> # A tibble: 1 × 1
#>   .pred
#>   <dbl>
#> 1  5.12

butchered <- butcher::butcher(fitted)
predict(butchered,  new_data = slice_sample(ames_test, n = 1))
#> Error in apply(post_dist, 2, mean, na.rm = TRUE): dim(X) must have a positive length
```

<sup>Created on 2023-08-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This reprex is probably too big right now for us to find the real problem but it's a place to start.

### PR DESCRIPTION
**Pull request by juliasilge**
Closes #262 

Turns out we need that `sigma` slot for predicting with `type = "ppd"` as well as for parsnip' `bart()`.

### CODE REVIEW

File: tests/testthat/test-bart.R [hunk 1]
```diff
@@ -32,4 +32,22 @@ test_that("dbarts + predict() works", {
     predict(x, newdata = head(mtcars))[1],
     predict(res, newdata = head(mtcars))[1]
   )
+  expect_equal(
+    mean(predict(x, newdata = head(mtcars), type = "ppd")),
+    mean(predict(res, newdata = head(mtcars), type = "ppd")),
```
Comment (juliasilge) [inline tests/testthat/test-bart.R:37]: Testing the mean because these predictions involve randomness.

File: tests/testthat/test-bart.R [hunk 2]
```diff
@@ -32,4 +32,22 @@ test_that("dbarts + predict() works", {
...
+
+test_that("bart() from parsnip + predict() works", {
+  library(parsnip)
+  spec <- bart(mode = "regression", trees = 5)
+  res <- fit(spec, mpg ~ ., mtcars)
+  x <- butcher(res)
+
+  expect_equal(
+    mean(predict(x, new_data = head(mtcars))$.pred),
+    mean(predict(res, new_data = head(mtcars))$.pred),
```
Comment (juliasilge) [inline tests/testthat/test-bart.R:50]: Same here:

``` r
library(parsnip)
## note that `bart()` has a pretty nasty namespace collision:
tidymodels::tidymodels_prefer()

spec <- bart(mode = "regression")
fitted <- fit(spec, mpg ~ ., mtcars)

predict(fitted, new_data = head(mtcars, n = 3))
#> # A tibble: 3 × 1
#>   .pred
#>   <dbl>
#> 1  20.8
#> 2  20.6
#> 3  24.4
predict(fitted, new_data = head(mtcars, n = 3))
#> # A tibble: 3 × 1
#>   .pred
#>   <dbl>
#> 1  20.8
#> 2  20.6
#> 3  24.6
predict(fitted, new_data = head(mtcars, n = 3))
#> # A tibble: 3 × 1
#>   .pred
#>   <dbl>
#> 1  20.7
#> 2  20.6
#> 3  24.6
```

<sup>Created on 2023-08-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by juliasilge** [comment]
@topepo I just pinged you for a review because Simon is OOO and we need to do a butcher release ahead of the rsample release. Let me know if you aren't able to take a look in the very near future!

File: tests/testthat/test-bart.R [hunk 3]
```diff
@@ -32,4 +32,22 @@ test_that("dbarts + predict() works", {
...
+  )
+})
+
+test_that("bart() from parsnip + predict() works", {
+  library(parsnip)
+  spec <- bart(mode = "regression", trees = 5)
+  res <- fit(spec, mpg ~ ., mtcars)
+  x <- butcher(res)
+
+  expect_equal(
```
Comment (topepo) [inline tests/testthat/test-bart.R:48]: I would add some tests with `predict(type = "conf_int")` and `predict(type = "pred_int")` too (just in case).

Comment (juliasilge) [reply tests/testthat/test-bart.R:48]: Thanks @topepo!
